server:
  port: 8081
spring:
  application:
    name: OAUTH2-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/IAM
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    generate-ddl: false
    properties:
      hibernate:
        cache:
      #    use_second_level_cache: true
       #   use_query_cache: true
        #  redisson:
          #  config: /etc/quara_wallet/redisson.yml
         # redis:
           # expiryInSeconds:
            #  authorization-service: 300
             # support-service: 300
         # region:
          #  factory_class: org.redisson.hibernate.RedissonRegionFactory
        ddl-auto: none  
        temp:
          use_jdbc_metadata_defaults: false
        format_sql: true  
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect